InternalClassType: Method
Coordinate3D: [-5,10,0]
Name: openConfig
Origin: 1f180de1-c9d7-4cf5-bc2a-85ee43e966ed
Program: |+1
 -- called by the context menu
 dialog.open
 Dialog.setIndex("Register",2)

RandomSeed: 69
UUID: 660efa8c-b98d-4015-bb60-1649adbed7cf
$SequenceNumber: 7
